version: '3.1'
services:
  db:
    image: postgres:10.6-alpine
    restart: always
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=movie-demo
  movie-service:
    build: .
    ports:
    - "80:8082"
    - "5432:5432"
    depends_on:
    - db
    environment:
    - DATABASE_HOST=db
    - DATABASE_NAME=movie-demo
    - DATABASE_PORT=5432
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=admin
