version: '2.0'
services:
  db:
    image: postgres:10.6-alpine
    restart: always
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=movie-demo
  movie-service:
    build: .
    ports:
    - "80:8082"
    depends_on:
    - db
    environment:
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=admin
