# H2
spring:
  application:
    name: movie-demo
  h2:
    console:
      enabled: true
      path: /h2

  # Datasource
  datasource:
    username: sa
    password:
    url: jdbc:h2:file:~/test
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: false
#    hibernate:
#      jdbc:
#        batch_size: 100
#      order_inserts: true
#      order_updates: true

server:
  port: 8082