spring:
  application:
    name: movie-demo
  data:
    rest:
      base-path: api

  # enable when ready for component testing
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2

  #    username: sa
  #    password:
  #    url: jdbc:h2:file:~/move-demo;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
  #    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 500
        order_inserts: true
        order_updates: true
    properties:
      hibernate:
        jdbc:
          lob:
            # see https://github.com/pgjdbc/pgjdbc/issues/1102
            non_contextual_creation: true

server:
  port: 8082

#logging:
#  level:
#    org:
#      springframework:
#        web: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: local
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/movie-demo
    username: postgres
    password: admin
---
spring:
  profiles: container
  datasource:
    platform: postgres
    url: jdbc:postgresql://db:5432/movie-demo
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}